parameters:
  terraformversion: '0.12.19'
  serviceprincipal: ''
  resourcegroup: ''
  storageAccountName: ''
  storageContainerName: ''
  storageKey: ''
  deployEnv: ''



jobs:
  - deployment: deploy_terraform
    continueonError: false
    environment: 'dev'
    strategy: 
    runOnce: 
      deploy:
      steps:
        - checkout: self
        - task: TerraformtaskV1@0
          displayName: 'init'
          inputs:
            terraformVersion: ${{ parameters.terraformversion }}
        - task: TerraformtaskV1@0
          displayName: init
          inputs: 
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: ${{ parameters.serviceprincipal}}            
            backendAzureRmResourceGroupName: ${{ parameters.resourcegroup }}           
            backendAzureRmStorageAccountName: ${{ parameters.storageAccountName }}
            backendAzureRmContainerName: ${{ parameters.storageContainerName }}
            backendAzureRmkey: ${{ parameters.storageKey }}
         - task: TerraformtaskV1@0
           displayName: 'plan'
           inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServicenameAzureRM: ${{ parameters.serviceprincipal }}
          - task: TerraformTaskV1@0
            displayName: 'apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServicenameAzureRM: ${{ parameters.serviceprincipal }}
